name: opensin-chat

networks:
  opensin-chat:
    driver: bridge

services:
  opensin-chat:
    container_name: opensin-chat
    restart: always
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
      args:
        ARG_UID: ${UID:-1000}
        ARG_GID: ${GID:-1000}
        SKIP_CHROMIUM: ${SKIP_CHROMIUM:-1}
    cap_add:
      - SYS_ADMIN
    volumes:
      - "./.env:/app/server/.env"
      - "../server/storage-opensin:/app/server/storage"
      - "../collector/hotdir/:/app/collector/hotdir"
      - "../collector/outputs/:/app/collector/outputs"
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "43939:3001"
    env_file:
      - .env
    environment:
      - STORAGE_DIR=/app/server/storage
    networks:
      - opensin-chat
    extra_hosts:
      - "host.docker.internal:host-gateway"