// SPDX-License-Identifier: MIT
// Purpose: Generated file download route handler.
// Extracted from document/index.js as part of issue #510 God-File split.

const consoleLogger = require("../../../utils/logger/console.js");
const { Telemetry } = require("../../../models/telemetry");
const { validApiKey } = require("../../../utils/middleware/validApiKey");
const createFilesLib = require("../../../utils/agents/aibitat/plugins/create-files/lib");

/**
 * Registers the generated-files download route on the Express app.
 * @param {import('express').Express} app
 */
function registerGeneratedFilesRoutes(app) {
  app.get(
    "/v1/document/generated-files/:filename",
    [validApiKey],
    async (request, response) => {
      /*
      #swagger.tags = ['Documents']
      #swagger.description = 'Download a file generated by an agent skill (e.g., PDF, DOCX, XLSX, PPTX). The filename is returned in the `outputs` array of a chat response when an agent generates a file. Use the `storageFilename` value from that response to download the file.'
      #swagger.parameters['filename'] = {
        in: 'path',
        description: 'The storage filename returned in the chat response outputs array (e.g., pdf-e9e14f28-d6b6-4f49-91a0-dd331517f567.pdf)',
        required: true,
        type: 'string'
      }
      #swagger.responses[200] = {
        description: 'File downloaded successfully',
        content: {
          "application/octet-stream": {
            schema: {
              type: 'string',
              format: 'binary'
            }
          }
        }
      }
      #swagger.responses[400] = {
        content: {
          "application/json": {
            schema: {
              type: 'object',
              example: {
                error: "Invalid filename format"
              }
            }
          }
        }
      }
      #swagger.responses[403] = {
        schema: {
          "$ref": "#/definitions/InvalidAPIKey"
        }
      }
      #swagger.responses[404] = {
        content: {
          "application/json": {
            schema: {
              type: 'object',
              example: {
                error: "File not found"
              }
            }
          }
        }
      }
      */
      try {
        const { filename } = request.params;
        if (!filename)
          return response.status(400).json({ error: "Filename is required" });

        const parsed = createFilesLib.parseFilename(filename);
        if (!parsed) {
          return response
            .status(400)
            .json({ error: "Invalid filename format" });
        }

        const fileData = await createFilesLib.getGeneratedFile(filename);
        if (!fileData) {
          return response.status(404).json({ error: "File not found" });
        }

        const mimeType = createFilesLib.getMimeType(`.${parsed.extension}`);
        const safeFilename = createFilesLib.sanitizeFilenameForHeader(filename);
        response.setHeader("Content-Type", mimeType);
        response.setHeader(
          "Content-Disposition",
          `attachment; filename="${safeFilename}"`,
        );
        response.setHeader("Content-Length", fileData.buffer.length);
        response.send(fileData.buffer);

        Telemetry.sendTelemetry("agent_generated_file_downloaded", {
          type: mimeType,
        }).catch((err) => {
          consoleLogger.error("Telemetry error:", err.message);
        });
      } catch (error) {
        consoleLogger.error(
          "[document/generated-files] Download error:",
          error.message,
        );
        return response.status(500).json({ error: "Failed to download file" });
      }
    },
  );
}

module.exports = { registerGeneratedFilesRoutes };
