#!/usr/bin/env bash
# SPDX-License-Identifier: MIT

# OpenSIN-Chat — Upstream Sync Patch Applier
# ------------------------------------------
# Applies the 6 atomic patch groups generated by `generate-patches.sh` in
# numerical order using `git am --3way`. Conflicts surface as normal merge
# markers and the maintainer resolves them. The script STOPS on the first
# conflict so you can fix it, commit, then re-run to continue.
#
# Docs: scripts/upstream-sync/upstream-sync.doc.md
# Strategy: docs/UPSTREAM-SYNC.md
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

PATCH_DIR="$SCRIPT_DIR/patches"
if [ ! -d "$PATCH_DIR" ] || [ -z "$(ls -A "$PATCH_DIR"/*.md 2>/dev/null)" ]; then
  echo "❌ No patches found in $PATCH_DIR"
  echo "   Run:  ./generate-patches.sh"
  exit 1
fi

# ── Pre-flight ──────────────────────────────────────────────────────
if ! git diff --quiet 2>/dev/null; then
  echo "❌ Working tree has uncommitted changes."
  echo "   Commit or stash before applying upstream sync."
  exit 1
fi

# Refuse to run on main — protect the production branch.
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [ "$CURRENT_BRANCH" = "main" ]; then
  echo "❌ Refusing to apply upstream sync directly to main."
  echo "   Create a branch first:  git checkout -b ref/upstream-sync-v1.13.x"
  exit 1
fi

# ── Apply in order ──────────────────────────────────────────────────
shopt -s nullglob
groups=("$PATCH_DIR"/[0-9][0-9]-*)
shopt -u nullglob

if [ "${#groups[@]}" -eq 0 ]; then
  echo "❌ No group directories in $PATCH_DIR"
  exit 1
fi

# Sort numerically so 01 < 02 < ... < 10
IFS=$'\n' groups=($(printf '%s\n' "${groups[@]}" | sort))
unset IFS

echo "→ Applying ${#groups[@]} group(s) on branch '$CURRENT_BRANCH' ..."
echo ""

for group in "${groups[@]}"; do
  gname="$(basename "$group")"
  echo "── $gname ──"

  shopt -s nullglob
  patches=("$group"/*.patch)
  shopt -u nullglob

  if [ "${#patches[@]}" -eq 0 ]; then
    echo "  (empty — nothing to apply)"
    continue
  fi

  # Sort by filename so 0001-... comes before 0002-...
  IFS=$'\n' patches=($(printf '%s\n' "${patches[@]}" | sort))
  unset IFS

  for patch in "${patches[@]}"; do
    pname="$(basename "$patch")"
    # Detect if patch is already applied by searching the patch's subject in
    # git history — both as a commit subject (HEAD) AND in commit bodies
    # (squash-merge imports leave original subjects as bullets in the body).
    # Using --stable git patch-id is more robust but slower; this heuristic
    # covers the typical squash-merge flow used by `gh pr merge --squash`.
    patch_subject=$(grep -m1 '^Subject: ' "$patch" | sed 's/^Subject: //' | sed 's/^\[PATCH[^]]*\] //')
    if [ -n "$patch_subject" ]; then
      if git log --all --oneline | grep -F "$patch_subject" >/dev/null 2>&1; then
        echo "  ⏭  $pname  (already applied: \"$patch_subject\")"
        continue
      fi
      if git log --all --format='%B' | grep -F "$patch_subject" >/dev/null 2>&1; then
        echo "  ⏭  $pname  (already applied in squash: \"$patch_subject\")"
        continue
      fi
    fi
    # --3way: use merge to apply even if the patch doesn't apply cleanly
    if git am --3way --quiet "$patch" 2>/dev/null; then
      echo "  ✓ $pname"
    else
      # If am is mid-conflict, auto-resolve by accepting HEAD content
      # (our rebrand wins over upstream strings). If the resulting tree
      # is identical to HEAD, the patch is a no-op (skip silently).
      if [ -d .git/rebase-apply ] || [ -d .git/sequencer ]; then
        # We're in a conflict. Auto-resolve all conflicted files to HEAD.
        conflicted=$(git diff --name-only --diff-filter=U 2>/dev/null)
        if [ -n "$conflicted" ]; then
          for f in $conflicted; do
            # Use git checkout --ours to keep HEAD content
            git checkout --ours -- "$f" 2>/dev/null
            git add "$f" 2>/dev/null
          done
          # Check if the resulting tree differs from HEAD
          if git diff --cached --quiet 2>/dev/null; then
            echo "  ⏭  $pname  (no-op: changes already in tree)"
            git am --skip --quiet 2>/dev/null || true
            continue
          fi
        fi
      fi
      echo "  ⚠  CONFLICT in $pname — resolve, commit, then re-run this script."
      echo "     Patch file: $patch"
      echo "     Tip:  git am --3way $patch   (with conflict markers in place)"
      exit 2
    fi
  done
done

echo ""
echo "✅ All patches applied on branch '$CURRENT_BRANCH'."
echo "   Verify, then:  git push origin $CURRENT_BRANCH"
