#!/usr/bin/env bash
# OpenAfD-Chat — Upstream Sync Patch Applier
# ------------------------------------------
# Applies the 6 atomic patch groups generated by `generate-patches.sh` in
# numerical order using `git am --3way`. Conflicts surface as normal merge
# markers and the maintainer resolves them. The script STOPS on the first
# conflict so you can fix it, commit, then re-run to continue.
#
# Docs: scripts/upstream-sync/upstream-sync.doc.md
# Strategy: docs/UPSTREAM-SYNC.md
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

PATCH_DIR="$SCRIPT_DIR/patches"
if [ ! -d "$PATCH_DIR" ] || [ -z "$(ls -A "$PATCH_DIR"/*.md 2>/dev/null)" ]; then
  echo "❌ No patches found in $PATCH_DIR"
  echo "   Run:  ./generate-patches.sh"
  exit 1
fi

# ── Pre-flight ──────────────────────────────────────────────────────
if ! git diff --quiet 2>/dev/null; then
  echo "❌ Working tree has uncommitted changes."
  echo "   Commit or stash before applying upstream sync."
  exit 1
fi

# Refuse to run on main — protect the production branch.
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [ "$CURRENT_BRANCH" = "main" ]; then
  echo "❌ Refusing to apply upstream sync directly to main."
  echo "   Create a branch first:  git checkout -b ref/upstream-sync-v1.13.x"
  exit 1
fi

# ── Apply in order ──────────────────────────────────────────────────
shopt -s nullglob
groups=("$PATCH_DIR"/[0-9][0-9]-*)
shopt -u nullglob

if [ "${#groups[@]}" -eq 0 ]; then
  echo "❌ No group directories in $PATCH_DIR"
  exit 1
fi

# Sort numerically so 01 < 02 < ... < 10
IFS=$'\n' groups=($(printf '%s\n' "${groups[@]}" | sort))
unset IFS

echo "→ Applying ${#groups[@]} group(s) on branch '$CURRENT_BRANCH' ..."
echo ""

for group in "${groups[@]}"; do
  gname="$(basename "$group")"
  echo "── $gname ──"

  shopt -s nullglob
  patches=("$group"/*.patch)
  shopt -u nullglob

  if [ "${#patches[@]}" -eq 0 ]; then
    echo "  (empty — nothing to apply)"
    continue
  fi

  # Sort by filename so 0001-... comes before 0002-...
  IFS=$'\n' patches=($(printf '%s\n' "${patches[@]}" | sort))
  unset IFS

  for patch in "${patches[@]}"; do
    pname="$(basename "$patch")"
    # --3way: use merge to apply even if the patch doesn't apply cleanly
    if git am --3way --quiet "$patch" 2>/dev/null; then
      echo "  ✓ $pname"
    else
      # Check if it's already applied (same commit already in our tree)
      sha_line=$(grep -m1 '^From [0-9a-f]' "$patch" | awk '{print $2}')
      if git log --oneline | grep -q "${sha_line:0:8}"; then
        echo "  ⏭  $pname  (already applied)"
        git am --skip --quiet 2>/dev/null || true
        continue
      fi
      echo "  ⚠  CONFLICT in $pname — resolve, commit, then re-run this script."
      echo "     Patch file: $patch"
      echo "     Tip:  git am --3way $patch   (with conflict markers in place)"
      exit 2
    fi
  done
done

echo ""
echo "✅ All patches applied on branch '$CURRENT_BRANCH'."
echo "   Verify, then:  git push origin $CURRENT_BRANCH"
